### ISSUE TITLE
Refactor `sign_and_notarize.py` for CI-Friendly Automation & GitHub Actions Release Flow

### ISSUE THREAD

**Issue by banagale** [banagale/FileKitty#59]
**Why this matters**

#43 yielded our current `tools/sign_and_notarize.py` works great on a developer’s laptop, but it relies on:

* a locally installed Developer ID certificate in the default keychain
* a pre-stored *NotaryProfile* in the keychain
* interactive environment variables that aren’t present in CI

To achieve one-click, repeatable releases triggered by a GitHub tag (or “Draft Release”), we need to refactor the script and add a dedicated **`release.yml` GitHub Actions workflow**. This will eliminate manual steps, prevent “works-on-my-machine” errors, and ensure every release artifact is notarized and stapled before users download it.

---

#### Scope of this refactor

1. **Parameterise secrets**

   * Accept `--apple-id`, `--app-password`, `--team-id` (or matching env vars) instead of relying on a saved keychain profile.
   * Accept an explicit `--p12-cert` (or `MACOS_CERT_BASE64`) + password so CI can import the Developer ID certificate.

2. **Separate stages inside the script**

   1. *Sign inside-out* (unchanged logic)
   2. Create **signed** DMG via `create-dmg` (now **without** `--notarize`)
   3. Run `xcrun notarytool submit --wait`
   4. Run `xcrun stapler staple` on the DMG

3. **Fail-fast validation**

   * After signing but before notarisation, run
     `codesign --verify --deep --strict` and abort on failure.

4. **Add CLI flags for CI**

   * `--no-sign` (keep)
   * `--notarize` (default false)
   * New secret flags/env look-ups for Apple ID and certificate password.

5. **Provide a reference GitHub Actions workflow (`.github/workflows/release.yml`)**

   * Triggers on `release: created`
   * Installs Python & Poetry, builds app, imports the `.p12` from a Base64-encoded repo secret, runs the refactored script with `--notarize`, then uploads `FileKitty-<tag>.dmg` as a release asset.

---

#### Acceptance Criteria

* [ ] Running `poetry run python tools/sign_and_notarize.py --no-sign` on CI completes without local keychain dependencies.
* [ ] Running the same script with
  `--notarize --apple-id $ID --app-password $PW --team-id $TEAM --p12-cert $P12 --p12-pass $CERT_PASS`
  produces a DMG that passes notarisation and staples successfully in CI.
* [ ] A new `release.yml` workflow builds, notarises, staples, and attaches the DMG to the published GitHub release asset list.
* [ ] Documentation / README updated with required GitHub Secrets (`MACOS_CERT_BASE64`, `MACOS_CERT_PASSWORD`, `NOTARY_APPLE_ID`, `NOTARY_APP_PASSWORD`, `NOTARY_TEAM_ID`).

---

**Out of scope**

* Further DMG artwork changes (covered by separate design tasks).
* Automating Homebrew formula bump—that remains in `tools/release.py`.

---

**Deliverables**

1. Refactored `tools/sign_and_notarize.py` (CI-aware).
2. Minimal `tools/entitlements.plist` referenced by the script.
3. `.github/workflows/release.yml` (macOS runner).
4. Updated docs describing how to export the `.p12` certificate and add GitHub Secrets.

Once merged, cutting a new GitHub Release tag should automatically publish a notarised, stapled DMG with zero local intervention.

**Comment by banagale** [comment]
Of course. This is a great question and the natural next step for your project. Moving this process into a CI/CD pipeline is the key to reliable, repeatable, and automated releases.

Your existing `sign_and_notarize.py` script is an excellent foundation, but it's built with a developer's local machine in mind. To make it work in the ephemeral, non-interactive environment of a CI runner, we need to address how it handles secrets and make it more explicit.

Here is a deep-dive into the recommended changes, following best practices for CI automation.

-----

### Part 1: Evolving the `sign_and_notarize.py` Script for CI

The primary challenge in CI is that the runner is a blank slate. It doesn't have your Developer ID certificate installed in a keychain, nor does it have your notarization credentials saved. The script currently finds these things implicitly; we need to modify it to accept them explicitly.

The best practice is to pass secrets to the script via environment variables or command-line arguments.

#### Recommended Script Modifications

Instead of relying on `create-dmg`'s `--notarize` shortcut, we'll make the script perform the notarization steps itself. This gives us finer control and makes the process more transparent.

1.  **Parameterize Notarization Credentials:** Modify the script to accept Apple ID, the app-specific password, and your Team ID as arguments.
2.  **Separate Notarization from DMG Creation:** The new flow within the script will be:
    a. Sign the app "inside-out" as before.
    b. Use `create-dmg` to create a **signed**, but **not yet notarized**, DMG.
    c. Call `xcrun notarytool` to submit the DMG for notarization.
    d. Wait for the submission to be approved.
    e. Call `xcrun stapler` to staple the notarization ticket to the DMG.

Here’s a conceptual rewrite of the relevant parts of `sign_and_notarize.py`.

```python
# ~/code/FileKitty/tools/packaging/sign_and_notarize.py (Conceptual Changes)

# ... imports
import os
import time

# ... existing helpers like run(), is_macho(), etc.

# --- MODIFIED: No longer use a hardcoded profile name ---
# NOTARY_PROFILE = "NotaryProfile" #<-- REMOVE THIS

# ... existing signing functions like sign_binaries_inside_out(), sign_outer_bundle() ...

# --- NEW: Functions for explicit notarization ---

def submit_for_notarization(dmg_path: Path, apple_id: str, app_password: str, team_id: str) -> str:
    """Submits the DMG to the Apple Notary Service and returns the submission UUID."""
    print(f"Submitting {dmg_path.name} for notarization...")
    cmd = [
        "xcrun", "notarytool", "submit",
        str(dmg_path),
        "--apple-id", apple_id,
        "--password", app_password,
        "--team-id", team_id,
        "--wait", # <-- Use --wait to simplify the process
        "--output-format", "json"
    ]
    # In a real CI, hide the password from logs if possible
    # For simplicity here, we print the command.
    print("$", " ".join(cmd).replace(app_password, "****"))
    
    res = run(cmd, capture=True)
    try:
        data = json.loads(res.stdout)
        if data["status"] == "Accepted":
            print(f"✅ Notarization successful for submission: {data['id']}")
            return data["id"]
        else:
            print("✖ Notarization failed.")
            print(res.stdout)
            sys.exit(1)
    except (json.JSONDecodeError, KeyError) as e:
        print(f"✖ Could not parse notarization response: {e}")
        print("STDOUT:", res.stdout)
        sys.exit(1)


def staple_ticket_to_dmg(dmg_path: Path) -> None:
    """Staples the notarization ticket to the given DMG."""
    print(f"Stapling notarization ticket to {dmg_path.name}...")
    run(["xcrun", "stapler", "staple", str(dmg_path)])
    print("✅ Stapling complete.")


# --- MODIFIED: create_dmg function ---
def create_dmg(settings: dict, *, skip_sign: bool) -> None:
    # This function now ONLY creates the DMG. Notarization is handled separately.
    if DMG_PATH.exists():
        DMG_PATH.unlink()
    # ... (setup staging dir as before)
    # ... (sign app bundle as before)

    args: list[str] = [ # ... (all the styling arguments as before) ]
    
    if not skip_sign:
        # We still have create-dmg sign the DMG itself
        args += ["--codesign", CERT_ID]
    
    # REMOVE the --notarize flag from here
    # if not skip_sign and not skip_notarize:
    #     args += ["--notarize", NOTARY_PROFILE]
        
    args += [str(DMG_PATH), str(STAGING)]
    run(args, cwd=ROOT)
    print("✅ Signed DMG created.")

# --- MODIFIED: CLI argument parsing ---
def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-sign", action="store_true")
    # Add new arguments for CI
    ap.add_argument("--notarize", action="store_true", help="Perform notarization after building DMG")
    ap.add_argument("--apple-id", help="Apple ID for notarization", default=os.getenv("NOTARY_APPLE_ID"))
    ap.add_argument("--app-password", help="App-specific password for notarization", default=os.getenv("NOTARY_APP_PASSWORD"))
    ap.add_argument("--team-id", help="Apple Developer Team ID", default=os.getenv("NOTARY_TEAM_ID"))
    return ap.parse_args()
    
# --- MODIFIED: main function ---
def main() -> None:
    args = parse_args()
    # ... (build and sign app bundle as before) ...
    
    # Step 1: Create the signed DMG
    create_dmg(load_dmg_settings(), skip_sign=args.no_sign)

    # Step 2: Optionally notarize and staple
    if args.notarize:
        if not all([args.apple_id, args.app_password, args.team_id]):
            sys.exit("✖ For notarization, --apple-id, --app-password, and --team-id are required.")
        
        submit_for_notarization(DMG_PATH, args.apple_id, args.app_password, args.team_id)
        staple_ticket_to_dmg(DMG_PATH)
        print("\n✅ DMG built, signed, notarized, and stapled.")
    else:
        print("\n✅ Signed DMG built for development (notarization skipped).")

```

This refactoring makes the script CI-aware. It can now run in a "build-only" mode or a "build and notarize" mode, driven by arguments that can be populated from CI secrets.

-----

### Part 2: The GitHub Actions Release Workflow

Your current `build.yml` is great for checking pull requests, but for releases, you need a dedicated workflow that handles secrets and uploads the final artifact.

Create a new file: `.github/workflows/release.yml`

```yaml
name: Release

# This workflow runs ONLY when a new Release is created in the GitHub UI
on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'poetry' # Enable caching for poetry

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Install Apple Certificate and Keychain
        env:
          MACOS_CERT_BASE64: ${{ secrets.MACOS_CERT_BASE64 }}
          MACOS_CERT_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
        run: |
          # Create a temporary keychain
          KEYCHAIN_PATH=$RUNNER_TEMP/app.keychain-db
          security create-keychain -p "${MACOS_CERT_PASSWORD}" ${KEYCHAIN_PATH}
          security set-keychain-settings -lut 21600 ${KEYCHAIN_PATH}
          security unlock-keychain -p "${MACOS_CERT_PASSWORD}" ${KEYCHAIN_PATH}

          # Decode and import the certificate
          echo ${MACOS_CERT_BASE64} | base64 --decode -o ./dist-cert.p12
          security import ./dist-cert.p12 -k ${KEYCHAIN_PATH} -P "${MACOS_CERT_PASSWORD}" -T /usr/bin/codesign
          rm ./dist-cert.p12

          # Make the keychain the default
          security list-keychains -s ${KEYCHAIN_PATH}
          security default-keychain -s ${KEYCHAIN_PATH}

      - name: Build the application with py2app
        run: poetry run python setup.py py2app

      - name: Sign, Notarize, and Package DMG
        env:
          NOTARY_APPLE_ID: ${{ secrets.NOTARY_APPLE_ID }}
          NOTARY_APP_PASSWORD: ${{ secrets.NOTARY_APP_PASSWORD }}
          NOTARY_TEAM_ID: ${{ secrets.NOTARY_TEAM_ID }}
        run: |
          poetry run python tools/packaging/sign_and_notarize.py --notarize
          # Rename the final DMG to include the release version/tag
          mv dist/FileKitty.dmg "dist/FileKitty-${{ github.event.release.tag_name }}.dmg"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/FileKitty-${{ github.event.release.tag_name }}.dmg
          asset_name: FileKitty-${{ github.event.release.tag_name }}.dmg
          asset_content_type: application/x-apple-diskimage

      - name: Clean up keychain
        if: always()
        run: |
          security delete-keychain $RUNNER_TEMP/app.keychain-db
```

#### How to Set Up This Workflow:

1.  **Add Secrets to GitHub:** Go to your `FileKitty` repository on GitHub, then `Settings > Secrets and variables > Actions`. Add the following repository secrets:

      * `MACOS_CERT_PASSWORD`: The password for your Developer ID certificate (`.p12` file).
      * `NOTARY_APPLE_ID`: The email address of the Apple ID used for notarization.
      * `NOTARY_APP_PASSWORD`: The **app-specific password** you generate at [[appleid.apple.com](https://www.google.com/search?q=https://appleid.apple.com)](https://www.google.com/search?q=https://appleid.apple.com). Do not use your main Apple ID password.
      * `NOTARY_TEAM_ID`: Your Apple Developer Team ID (e.g., `A1B2C3D4E5`).
      * `MACOS_CERT_BASE64`: This one is tricky. You need to provide your `.p12` certificate file as a single line of text.
        1.  Export your "Developer ID Application" certificate from Keychain Access on your Mac as a `.p12` file.
        2.  On your terminal, run this command: `base64 -i /path/to/your/certificate.p12 | pbcopy`
        3.  Paste the result (which is a very long, single line of text) as the value for this secret.

2.  **Commit the Workflow:** Add the `release.yml` file to your `.github/workflows/` directory.

3.  **Trigger the Release:** Now, your release process is fully automated. When you are ready to release a new version:

    1.  Go to the "Releases" page of your GitHub repository.
    2.  Click "Draft a new release."
    3.  Create a new tag (e.g., `v0.2.4`).
    4.  Add release notes.
    5.  Click **"Publish release"**.

This action will trigger the `release.yml` workflow, which will securely build, sign, notarize, and upload the final `FileKitty-v0.2.4.dmg` directly to the assets of the release you just created.
